name: Check file length

on:
  push:
  workflow_dispatch:

jobs:
  check_file_length:
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install bash curl git python3 python3-pip
    - name: Pull repository (1)
      uses: actions/checkout@v2
    - name: Get GraduatorieScript
      run: curl -Lo to_run.py https://raw.githubusercontent.com/PoliNetworkOrg/CheckFilesLength/master/main.py
    - name: Run aggiorna_graduatorie.py
      run: python3 ./to_run.py
