name: Comment on PR with ClickUp task
on:
    pull_request:
        types: [opened, reopened]

jobs:
    comment:
        name: Comment on PR with ClickUp task
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/github-script@v6
              id: my-script
              with:
                  result-encoding: string
                  retries: 3
                  script: |
                      console.log(process.env.GITHUB_REF_NAME);
