name: Publish
on:
  push:

jobs:
  publish:
    name: Publish via EAS updates
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: pnpm install --frozen-lockfile
      - name: Publish via EAS updates
        run: eas update --auto
