name: Publish
on:
  push:

jobs:
  publish:
    name: Publish via EAS updates
    runs-on: ubuntu-20.04
    # only run if expo token is set
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ env.EXPO_TOKEN }}

      - run: yarn install --immutable

      - name: Check if Dependabot triggered this action
        run: |
          if [ "${{ github.actor }}" = "dependabot[bot]" ]; then
            echo "Dependabot triggered this action. Skipping..."
            exit 0
          fi
        shell: bash

      - name: Check if PR is from a fork
        run: |
          if [[ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
            echo "PR is from a fork, skipping the workflow"
            exit 78  # This exit code will skip the workflow
          fi
        shell: bash
      
      - name: Publish via EAS updates
        run: eas update --auto
